version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - yarn install
  pre_build:
    commands:
      - echo "Starting pre-build phase"
  build:
    commands:
      - echo "Starting build phase"
      - yarn run build
      - set -x
      - sleep 360 # Sleeps for 6 minutes, exceeding the 5-minute limit
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: out

cache:
  paths:
    - "node_modules/**/*"
    - ".next/cache/**/*"
